### ISSUE TITLE
Add multiple sites in this config

### ISSUE THREAD

**Issue by pidupuis** [mihaics/docker-owncloud#2]
Your docker-compose.yml is by far the most efficient and easy-to-use config file I've seen to deploy owncloud over nginx and let's encrypt.

But I can't manage to deploy other services (gitlab, icescrum, hexo, ...). Even by having multiple VIRTUAL_HOSTS, not only it does not work but owncloud does not work anymore. How would you distribute multiple sites using your config?

Thanks in advance.

**Comment by mihaics** [comment]
Hi, 

well, will have to see, because I just deployed wordpress using the same approach, and now we have the requirement to deploy other websites, different url-s and different docker nodes/web server software. Hope will scale, especially with letsencrypt, I will get back once is working and documented.

Cheers,
Mihai

**Comment by pidupuis** [comment]
Cool! I'll wait for it :)
